/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

const sidebars = 
{
  docs: 
  [
    'introduction',
    {
      type: 'category',
      label: 'Projects',
      link: 
      {
        type: 'generated-index',
        title: 'My Projects',
        description: 'Description and documentation of all of my projects',
        keywords: ['documentation, description'],
      },
      collapsed: false,
      items: 
      [
        {
          type: 'category',
          label: 'Arch Linux GUI',
          link: 
          {
            type: 'doc',
            id: 'projects/arch-linux-gui/about-alg',
          },
          items: 
          [
            'projects/arch-linux-gui/build-alg-iso',
            'projects/arch-linux-gui/build-installer',
            'projects/arch-linux-gui/installer-config',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Code',
      link:
      {
        type: 'generated-index',
        title: 'Langs & Tools',
        description: 'Reference documents for various tools & languages',
        keywords: ['documentation, description'],
      },
      collapsed: true,
      items: 
      [
        {
          type: 'category',
          label: 'Tools & Utilities',
          link: 
          {
            type: 'generated-index',
            title: 'Tools & Utilities',
            description: 'Reference documents for various tools used in the world of code',
            keywords: ['version-control, tools'],
          },
          items: 
          [
            'code/tools/git',
            'code/tools/markdown',
          ],
        },
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Tutorials',
    //   link:
    //   {
    //     type: 'generated-index',
    //     title: 'Tutorials',
    //     description: 'Tutorial documents to supplement my technical youtube videos',
    //     keywords: ['tutorials, youtube'],
    //   },
    //   collapsed: true,
    //   items: 
    //   [
    //     'tutorials/db-win-linux_mint'
    //   ],
    // },
  ],
};

module.exports = sidebars;